# Change baseurl before deploy
baseurl="/"
# baseurl = "https://game1991.github.io/CodeImp"
enableGitInfo  =true
enableRobotsTXT=true
languageCode   ="zh-cn"
timeout        ="10m"
title          ="代码无界限"


# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage="zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage=true

# Change it to your Disqus shortname before using
disqusShortname="TechSphere"

[pagination]
    pagerSize=5
